/**
 * Export entry point for static HTML output.
 * Reads execution data from window.__pdit_response__ (injected by pdit export).
 * No networking, no editor - just renders the output.
 */
import { createRoot } from 'react-dom/client'
import React from 'react'
import { OutputPane } from './OutputPane'
import { Expression } from './execution'
import { LineGroup, computeLineGroups } from './compute-line-groups'
import './style.css'

declare global {
  interface Window {
    __pdit_response__?: {
      code: string
      expressions: Expression[]
    }
  }
}

function ExportApp() {
  const data = window.__pdit_response__

  if (!data) {
    return (
      <div style={{ padding: '20px', fontFamily: 'monospace' }}>
        Error: No execution data found. This page should be generated by `pdit export`.
      </div>
    )
  }

  const { expressions } = data
  const lineGroups: LineGroup[] = computeLineGroups(expressions)

  return (
    <div id="app">
      <div className="split-container reader-mode">
        <div className="editor-half editor-hidden" />
        <div className="output-half output-full">
          <OutputPane
            expressions={expressions}
            lineGroups={lineGroups}
            readerMode={true}
          />
        </div>
      </div>
    </div>
  )
}

const container = document.getElementById('app')!
const root = createRoot(container)
root.render(<ExportApp />)
